# Quiz 8: Get SQL and BigQuery To Work  
### Bibek Thapa

In this notebook, we will:

- Create and use a Google Cloud project to run BigQuery queries  
- Navigate to the dataset `bigquery-public-data.austin_bikeshare.bikeshare_trips`  
- Compute how many entries are in the dataset  
- Compute the longest trip using `duration_minutes`  
- Compute the average trip time using `duration_minutes`

In [11]:
from google.colab import auth
auth.authenticate_user()
print("Authenticated")

Authenticated

In [12]:
%%bigquery --project quiz8-bigquery
SELECT COUNT(*) AS total_rows
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`;

Query is running:   0%|          |

Downloading:   0%|          |

   total_rows
0     2271152

In [13]:
%%bigquery --project quiz8-bigquery
SELECT MAX(duration_minutes) AS longest_trip_minutes
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`;

Query is running:   0%|          |

Downloading:   0%|          |

   longest_trip_minutes
0                 34238

In [14]:
%%bigquery --project quiz8-bigquery
SELECT ROUND(AVG(duration_minutes), 2) AS avg_trip_minutes
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`;

Query is running:   0%|          |

Downloading:   0%|          |

   avg_trip_minutes
0             28.72